//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBanking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public int CustomerId { get; set; }
        public decimal AccountNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string AccountType { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
