//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBanking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iBankingEntities : DbContext
    {
        public iBankingEntities()
            : base("name=iBankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<CustomerAccount> CustomerAccounts { get; set; }
        public virtual DbSet<Debit> Debits { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FixedDeposit> FixedDeposits { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
